language: java
notifications:
  irc:
    channels:
      - "irc.freenode.org#jnr"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
matrix:
  include:
  - os: linux
    jdk: openjdk6
  - os: linux
    jdk: openjdk7
  - os: linux
    jdk: oraclejdk7
  - os: linux
    jdk: oraclejdk8
  - os: linux
    services:
    - docker
    before_install:
    - docker pull ibmcom/ibmjava:8-sdk
    script:
    - docker run -v `pwd`:/work ibmcom/ibmjava:8-sdk /bin/sh -c "cd work; ant test"

sudo: required
cache:
  directories:
  - $HOME/.m2
